---
services:
  pg:
    container_name: go_downloader_pg_db
    image: postgres:latest
    ports:
      - '5432:5432'
    networks:
      - web
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - go_downloader_pg_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  go_downloader_pg_data:

networks:
  web:
    external: true