name: CI Pipeline for running Tests

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.23.x' ]

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Display Go version
        run: go version

      - name: Create a dist dir with random file 
        run: |
          mkdir -p dist
          echo "placeholder content" > dist/_placeholder.txt

      - name: Install Dependencies
        run: go mod tidy
      
      - name: Run Tests
        run: go test -v ./...